/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calc_model_Calculator */

#ifndef _Included_calc_model_Calculator
#define _Included_calc_model_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calc_model_Calculator
 * Method:    calculate
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_calc_model_Calculator_calculate
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     calc_model_Calculator
 * Method:    verification
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_calc_model_Calculator_verification
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
