/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calc_model_CreditCalculator */

#ifndef _Included_calc_model_CreditCalculator
#define _Included_calc_model_CreditCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calc_model_CreditCalculator
 * Method:    calculate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_calc_model_CreditCalculator_calculate
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
